### ISSUE TITLE
Numpy 2.0 breaks osier

### ISSUE THREAD

**Issue by victoraalves** [arfc/osier#59]
Hi,

When running the tests after installing osier by following the installation instructions, I have the following error:

`AttributeError: np.float_ was removed in the NumPy 2.0 release. Use np.float64 instead.`

Which can be fixed by installing a pre-2.0 numpy version. I installed 1.26.4 and this seemed to fix the issue.

The definitive solution would be to follow the recommendation of using `np.float64` as suggested by numpy itself.

**Comment by samgdotson** [comment]
Thanks @victoraalves for creating this issue and identifying the dependency conflict.
I believe this error comes from a conflict in Pyomo, rather than Osier https://github.com/Pyomo/pyomo/issues/3290. I believe pinning Numpy < 2.0 will resolve the problem. I am working on updating the installer for osier.
