### ISSUE TITLE
Pymoo Compilation Error

### ISSUE THREAD

**Issue by ceserz2** [arfc/osier#61]
Upon running the capacity expansion tutorial, the following message was shown:
"Compiled modules for significant speedup can not be used!
https://pymoo.org/installation.html#installation

To disable this warning:
from pymoo.config import Config
Config.warnings['not_compiled'] = False"

The running time for the algorithm was a minute longer than the tutorial, meaning running larger simulations would take much more time.

**Comment by ceserz2** [comment]
looking to the Pymoo Installation website provided. Ran following command in the terminal:
`python -c "from pymoo.util.function_loader import is_compiled;print('Compiled Extensions: ', is_compiled())"
`
But I recieved the following message: `Compiled Extensions:  False`

**Comment by samgdotson** [comment]
This seems like an issue with `pymoo` rather than `osier`. I ran the command you listed and received the following output:

```bash
samdotson@Sams-MacBook-Pro-3 research % python -c "from pymoo.util.function_loader import is_compiled;print('Compiled Extensions: ', is_compiled())"
Compiled Extensions:  True
```

Additionally, in order to be more helpful I need to know
- what operating system you're using
- what version of python you have
- what steps you took to produce the error
- what you have tried to do to rectify the issue

As of right now, I can't replicate the problem.
